### ISSUE TITLE
Add automatic normalization of the response matrix

### ISSUE THREAD

**Issue by JustWhit3** [JustWhit3/QUnfold#10]
The response matrix given as argument to the [`QUnfoldQUBO`](https://github.com/JustWhit3/QUnfold/blob/main/src/QUnfold/core/QUnfoldQUBO.py) class is supposed to be normalized, otherwise the algorithm may fails in its purpose. However it may happens that input data are not normalized and the user doesn't know how to normalize them. A possible solution is to implement an automatic normalization procedure to the input matrix in order to always have a convergent result.

**Comment by SimoneGasperini** [comment]
See the function added in the module [`src/QUnfold/utility/tools.py`](https://github.com/JustWhit3/QUnfold/blob/main/src/QUnfold/utility/tools.py).
